// <auto-generated />
namespace Gamepad.Service.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changeProfile : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changeProfile));
        
        string IMigrationMetadata.Id
        {
            get { return "201510210712122_changeProfile"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
