//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamepad.Service.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gamepad.Service.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این نوع فایل قابل قبول نیست..
        /// </summary>
        public static string Services_File_UnacceptableFileType {
            get {
                return ResourceManager.GetString("Services_File_UnacceptableFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات تکراری است..
        /// </summary>
        public static string Services_General_Duplicate {
            get {
                return ResourceManager.GetString("Services_General_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} وجود دارد..
        /// </summary>
        public static string Services_General_Existed_ {
            get {
                return ResourceManager.GetString("Services_General_Existed_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات ورودی نادرست است..
        /// </summary>
        public static string Services_General_InputData {
            get {
                return ResourceManager.GetString("Services_General_InputData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موردی یافت نشد..
        /// </summary>
        public static string Services_General_ItemNotFound {
            get {
                return ResourceManager.GetString("Services_General_ItemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} مورد نظر قابل حذف نیست..
        /// </summary>
        public static string Services_General_NonDeletable_ {
            get {
                return ResourceManager.GetString("Services_General_NonDeletable_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} مورد نظر یافت نشد..
        /// </summary>
        public static string Services_General_NotFound_ {
            get {
                return ResourceManager.GetString("Services_General_NotFound_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطای سیستمی رخ داد..
        /// </summary>
        public static string Services_General_OperationError {
            get {
                return ResourceManager.GetString("Services_General_OperationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آواتار وجود ندارد..
        /// </summary>
        public static string Services_User_AvatarNotFound {
            get {
                return ResourceManager.GetString("Services_User_AvatarNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این آدرس ایمیل قبلا ثبت شده است..
        /// </summary>
        public static string Services_User_EmailExisted {
            get {
                return ResourceManager.GetString("Services_User_EmailExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پسورد درست نیست..
        /// </summary>
        public static string Services_User_InvalidPassword {
            get {
                return ResourceManager.GetString("Services_User_InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات پروفایل قابل قبول نیست..
        /// </summary>
        public static string Services_User_ProfileInvalidData {
            get {
                return ResourceManager.GetString("Services_User_ProfileInvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پروفایلی برای این کاربر ثبت نشده است..
        /// </summary>
        public static string Services_User_ProfileNotFound {
            get {
                return ResourceManager.GetString("Services_User_ProfileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این کاربر تائید نشده است..
        /// </summary>
        public static string Services_User_Unconfirmed {
            get {
                return ResourceManager.GetString("Services_User_Unconfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این نام کاربری قفل است..
        /// </summary>
        public static string Services_User_UserIsLocked {
            get {
                return ResourceManager.GetString("Services_User_UserIsLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این نام کاربری قبلا ثبت شده است..
        /// </summary>
        public static string Services_User_UsernameExisted {
            get {
                return ResourceManager.GetString("Services_User_UsernameExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربری یافت نشد..
        /// </summary>
        public static string Services_User_UserNotFound {
            get {
                return ResourceManager.GetString("Services_User_UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} را مشخص کنید..
        /// </summary>
        public static string Validation_General_Mandatory {
            get {
                return ResourceManager.GetString("Validation_General_Mandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} را به درستی وارد کنید..
        /// </summary>
        public static string Validation_General_RegularExperssion {
            get {
                return ResourceManager.GetString("Validation_General_RegularExperssion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} را وارد کنید..
        /// </summary>
        public static string Validation_General_Required {
            get {
                return ResourceManager.GetString("Validation_General_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداکثر می تواند {1} کارکتر داشته باشد..
        /// </summary>
        public static string Validation_General_StringLength {
            get {
                return ResourceManager.GetString("Validation_General_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداقل {2} و حداکثر {1} کارکتر قابل قبول است..
        /// </summary>
        public static string Validation_General_StringLengthBound {
            get {
                return ResourceManager.GetString("Validation_General_StringLengthBound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پسورد با تکرار آن منطبق نیست..
        /// </summary>
        public static string Validation_User_ComparePass {
            get {
                return ResourceManager.GetString("Validation_User_ComparePass", resourceCulture);
            }
        }
    }
}
